[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd client && npm install --legacy-peer-deps || npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd client && NODE_OPTIONS='--max-old-space-size=4096' CI=false GENERATE_SOURCEMAP=false INLINE_RUNTIME_CHUNK=false npm run build"
]

[start]
cmd = "cd server && NODE_ENV=production node index.js"
